export const SET_TOKEN = 'SET_TOKEN'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_F = 'GET_PRODUCTS_F'
export const GET_PRODUCTS_R = 'GET_PRODUCTS_R'
