export const PING = 'PING'
export const PING_F = 'PING_F'
export const PONG = 'PONG'
export const PONG_F = 'PONG_F'
export const SET_TOKEN = 'SET_TOKEN'

export const SET_PRODUCTS = 'SET_PRODUCTS'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_F = 'GET_PRODUCTS_F'
export const GET_PRODUCTS_R = 'GET_PRODUCTS_R'
